name: Deploy Amazon Image Scraper to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List directory structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Checking for paste-and-pixl directory:"
          if [ -d "paste-and-pixl" ]; then
            echo "paste-and-pixl directory found"
            ls -la paste-and-pixl/
          else
            echo "paste-and-pixl directory not found"
            echo "Available directories:"
            find . -type d -maxdepth 2
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: paste-and-pixl/package-lock.json

      - name: Install dependencies
        run: |
          if [ -d "paste-and-pixl" ]; then
            cd paste-and-pixl
            npm ci
          else
            echo "paste-and-pixl directory not found, trying to install from root"
            npm ci
          fi

      - name: Build
        run: |
          if [ -d "paste-and-pixl" ]; then
            cd paste-and-pixl
            npm run build
          else
            echo "paste-and-pixl directory not found, trying to build from root"
            npm run build
          fi
        env:
          VITE_SUPABASE_URL: https://vkmvppllfwldzyzqnveo.supabase.co
          VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrbXZwcGxsZndsZHp5enFudmVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1ODkzNDQsImV4cCI6MjA3NTE2NTM0NH0.hiqB2w5lQ205QVvuok4hAJ566ocQ20asBLZcYkDkmh0

      - name: Check build output
        run: |
          echo "Checking for dist directory:"
          if [ -d "paste-and-pixl/dist" ]; then
            echo "paste-and-pixl/dist found"
            ls -la paste-and-pixl/dist/
          elif [ -d "dist" ]; then
            echo "dist directory found in root"
            ls -la dist/
          else
            echo "No dist directory found"
            find . -name "dist" -type d
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: paste-and-pixl/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4